In [1]:
from scipy import sparse
import numpy as np
import time
import scipy as sp


In [70]:
class fm_tool(object):
    def __init__(self,epochs=5,learningRate=0.01):
        self.epochs = epochs
        self.learningRate = learningRate

        
    def data_type(self,data):
        if not type(data) is sp.sparse.csr.csr_matrix:
            return sparse.csr_matrix(data)
        else:
            return data
        
        
    def predict_raw(self,TrainX):
        trainX = self.data_type(data=TrainX)
        result = (trainX*self.weight_first) + self.weight_constant + 0.5*(np.power(trainX*self.weight_second.T,2)-trainX.power(2)*np.power(self.weight_second,2).T).sum(axis=1)
        return result
    
    def predict(self,TrainX):
        trainX = self.data_type(data=TrainX)
        return (1/(1+np.exp(-1*self.predict_raw(trainX))))
        
    def fit(self,TrainX,Trainy,k,ValX=None,Valy=None,verbose=False):
        ###init the model
        self.k = k
        trainX = self.data_type(data=TrainX)
        #trainyTmp = trainy.reshape(trainy.shape[0],1)
        trainyTmp = np.matrix(Trainy).T
        baseMatrix = np.matrix([1]*trainX.shape[1])
        self.weight_constant = 0
        self.weight_first = np.matrix(np.random.randn(trainX.shape[1])).T
        self.weight_second = np.matrix(np.random.randn(self.k,trainX.shape[1]))
        
        for n in range(self.epochs):
            start_time = time.time()
            gradientBase = -1*trainyTmp + self.predict(trainX)
            self.learningRate = 0.9*self.learningRate
            
            recordTmp = trainX.T
            #gradientBaseTmp = gradientBase
            

            gradientInteraction = self.weight_second*recordTmp
            
            
            weight_constant_change = self.learningRate*gradientBase
            weight_first_change = recordTmp*self.learningRate*gradientBase
            
            print(gradientInteraction.shape)
            print(np.matrix(np.column_stack([gradientBase[i,0]*np.eye(self.k)] for i in range(gradientBase.shape[0]))[0]).shape)
            print((recordTmp*gradientInteraction.T-recordTmp.power(2)*np.eye(trainX.shape[1])*self.weight_second.T).T.shape)
            self.weight_second_change = self.learningRate*np.matrix(np.column_stack([gradientBase[i,0]*np.eye(self.k)] for i in range(gradientBase.shape[0]))[0])*(recordTmp*gradientInteraction.T-recordTmp.power(2)*baseMatrix*self.weight_second.T).T
            
            
            
            
            
            '''for i in range(trainX.shape[0]):
                print(i)
                recordTmp = trainX[i].T
                gradientBaseTmp = gradientBase[i]
                          
                
                gradientInteraction = self.weight_second*recordTmp
                
                self.weight_constant = self.weight_constant - self.learningRate*gradientBaseTmp
                self.weight_first = self.weight_first - recordTmp*self.learningRate*gradientBaseTmp
                self.weight_second = self.weight_second - self.learningRate*gradientBaseTmp[0,0]*(recordTmp*gradientInteraction.T-recordTmp.power(2)*baseMatrix*self.weight_second.T).T'''
            if verbose:
                print('epoch--%d in %.2f s'%(n,time.time()-start_time))
                print('Train Set accuracy: %.4f'%self.accuracy(trainX,Trainy))
                try: print('Validation Set accuracy: %.4f'%self.accuracy(valX,valy))
                except: continue
            
    def accuracy(self,TrainX,Trainy):
        trainX = self.data_type(data=TrainX)
        trainyTmp = np.matrix(Trainy).T
        return -1*(np.log(1- trainyTmp-self.predict(trainX)+2*(trainyTmp*self.predict(trainX).T).diagonal().T).mean())

In [72]:
class fm_tool(object):
    def __init__(self,epochs=5,learningRate=0.01):
        self.epochs = epochs
        self.learningRate = learningRate

        
    def data_type(self,data):
        if not type(data) is sp.sparse.csr.csr_matrix:
            return sparse.csr_matrix(data)
        else:
            return data
        
        
    def predict_raw(self,TrainX):
        trainX = self.data_type(data=TrainX)
        result = (trainX*self.weight_first) + self.weight_constant + 0.5*(np.power(trainX*self.weight_second.T,2)-trainX.power(2)*np.power(self.weight_second,2).T).sum(axis=1)
        return result
    
    def predict(self,TrainX):
        trainX = self.data_type(data=TrainX)
        return (1/(1+np.exp(-1*self.predict_raw(trainX))))
        
    def fit(self,TrainX,Trainy,k,ValX=None,Valy=None,verbose=False):
        ###init the model
        self.k = k
        trainX = self.data_type(data=TrainX)
        #trainyTmp = trainy.reshape(trainy.shape[0],1)
        trainyTmp = np.matrix(Trainy).T
        baseMatrix = np.matrix([1]*trainX.shape[1])
        self.weight_constant = 0
        self.weight_first = np.matrix(np.random.randn(trainX.shape[1])).T
        self.weight_second = np.matrix(np.random.randn(self.k,trainX.shape[1]))
        
        for n in range(self.epochs):
            start_time = time.time()
            gradientBase = -1*trainyTmp + self.predict(trainX)
            self.learningRate = 0.9*self.learningRate
            for i in range(trainX.shape[0]):

                recordTmp = trainX[i].T
                gradientBaseTmp = gradientBase[i]
                          
                
                gradientInteraction = self.weight_second*recordTmp
                
                self.weight_constant = self.weight_constant - self.learningRate*gradientBaseTmp
                self.weight_first = self.weight_first - recordTmp*self.learningRate*gradientBaseTmp
                self.weight_second = self.weight_second - self.learningRate*gradientBaseTmp[0,0]*(recordTmp*gradientInteraction.T-recordTmp.power(2)*baseMatrix*self.weight_second.T).T
            if verbose:
                print('epoch--%d in %.2f s'%(n,time.time()-start_time))
                print('Train Set accuracy: %.4f'%self.accuracy(trainX,Trainy))
                try: print('Validation Set accuracy: %.4f'%self.accuracy(valX,valy))
                except: continue
            
    def accuracy(self,TrainX,Trainy):
        trainX = self.data_type(data=TrainX)
        trainyTmp = np.matrix(Trainy).T
        return -1*(np.log(1- trainyTmp-self.predict(trainX)+2*(trainyTmp*self.predict(trainX).T).diagonal().T).mean())

In [73]:
fm =fm_tool(learningRate=0.01,epochs=100)
fm.fit(TrainX=np.random.randn(200).reshape(20,10),Trainy=np.array([0]*10+[1]*10),k=32,verbose=True)

epoch--0 in 0.01 s
Train Set accuracy: 7.3843
epoch--1 in 0.01 s
Train Set accuracy: 4.8456
epoch--2 in 0.01 s
Train Set accuracy: 3.2987
epoch--3 in 0.01 s
Train Set accuracy: 2.7932
epoch--4 in 0.01 s
Train Set accuracy: 2.2958
epoch--5 in 0.01 s
Train Set accuracy: 1.8786
epoch--6 in 0.01 s
Train Set accuracy: 1.5844
epoch--7 in 0.01 s
Train Set accuracy: 1.4758
epoch--8 in 0.01 s
Train Set accuracy: 1.4279
epoch--9 in 0.01 s
Train Set accuracy: 1.3933
epoch--10 in 0.01 s
Train Set accuracy: 1.3606
epoch--11 in 0.01 s
Train Set accuracy: 1.3308
epoch--12 in 0.01 s
Train Set accuracy: 1.3033
epoch--13 in 0.01 s
Train Set accuracy: 1.2782
epoch--14 in 0.01 s
Train Set accuracy: 1.2553
epoch--15 in 0.01 s
Train Set accuracy: 1.2343
epoch--16 in 0.01 s
Train Set accuracy: 1.2152
epoch--17 in 0.01 s
Train Set accuracy: 1.1978
epoch--18 in 0.01 s
Train Set accuracy: 1.1819
epoch--19 in 0.01 s
Train Set accuracy: 1.1676
epoch--20 in 0.01 s
Train Set accuracy: 1.1545
epoch--21 in 0.01 s
Tra

In [ ]:
fm.predict(np.random.randn(200).reshape(20,10))

In [48]:
fm.gradientBase[1,0]

1.7515726905035353e-17

In [57]:
np.matrix(np.column_stack([fm.gradientBase[i,0]*np.eye(32)] for i in range(fm.gradientBase.shape[0]))[0]).shape

(640, 32)

In [ ]:
a = np.array([1]*100).reshape(10,10)

In [ ]:
type(a) is np.ndarray

In [ ]:
for i in range(a.shape[0]):
    a[i,:i+1] = 0
a

In [ ]:
b = np.matrix(a)
c = np.matrix(a+1)

In [ ]:
b = np.matrix(b)
b

In [5]:
import numpy as np
from scipy import sparse
A = np.matrix([1,2,0])
B = np.matrix([[1,2,0],[0,0,3],[1,0,4],[1,2,3]])

In [6]:
sA = sparse.csr_matrix(A)
sB = sparse.csr_matrix(B)
sC =sB

In [38]:
np.row_stack([A,A]).shape

(2, 3)

In [30]:
c = np.matrix([A,A,A])
c.shape

ValueError: matrix must be 2-dimensional

In [67]:
for i in range(sB.shape[0]):
    sB[i,i:] = 0
sB.todense()

C:\Users\Leo Mao\Anaconda3\lib\site-packages\scipy\sparse\compressed.py:774: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)


matrix([[0, 0, 0],
        [0, 0, 0],
        [1, 0, 0]], dtype=int32)

In [86]:
sB*B.T

matrix([[ 5,  0,  1,  5],
        [ 0,  9, 12,  9],
        [ 1, 12, 17, 13],
        [ 5,  9, 13, 14]], dtype=int32)

In [80]:
sB.sum(axis=0)

matrix([[ 3,  4, 10]], dtype=int32)

In [54]:
np.repeat(sB)

TypeError: repeat() missing 1 required positional argument: 'repeats'

In [ ]:
sA.T*sA

In [ ]:
t.sum(axis=0)

In [41]:
help(B)

Help on matrix in module numpy.matrixlib.defmatrix object:

class matrix(numpy.ndarray)
 |  matrix(data, dtype=None, copy=True)
 |  
 |  Returns a matrix from an array-like object, or from a string of data.
 |  A matrix is a specialized 2-D array that retains its 2-D nature
 |  through operations.  It has certain special operators, such as ``*``
 |  (matrix multiplication) and ``**`` (matrix power).
 |  
 |  Parameters
 |  ----------
 |  data : array_like or string
 |     If `data` is a string, it is interpreted as a matrix with commas
 |     or spaces separating columns, and semicolons separating rows.
 |  dtype : data-type
 |     Data-type of the output matrix.
 |  copy : bool
 |     If `data` is already an `ndarray`, then this flag determines
 |     whether the data is copied (the default), or whether a view is
 |     constructed.
 |  
 |  See Also
 |  --------
 |  array
 |  
 |  Examples
 |  --------
 |  >>> a = np.matrix('1 2; 3 4')
 |  >>> print(a)
 |  [[1 2]
 |   [3 4]]
 |  
 | 

In [ ]:
B

In [ ]:
B+B

In [ ]:
fm.predict(np.random.randn(200).reshape(20,10))

In [ ]:
fm.recordTmp.shape

In [ ]:
fm.gradientBase[1].shape

In [64]:
class Fib(object):
    def __getitem__(self, n):
        if isinstance(n, int):
            a, b = 1, 1
            for x in range(n):
                a, b = b, a + b
                return a
        elif isinstance(n, slice):
            start = n.start
            stop = n.stop
            a, b = 1, 1
            L = []
            for x in range(stop):
                if x >= start:
                    L.append(a)
                    a, b = b, a + b
            return L
        else:
            raise TypeError("Fib indices must be integers")
   
   
test = Fib()
print(test[0:10])

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


In [ ]:
a

In [ ]:
b

In [ ]:
a = np.arange(200).reshape(20,10)
b = np.arange(10).reshape(10,1)

In [ ]:
(a.T*b).sum(axis=0).reshape(,1)

In [ ]:
b[0].reshape(2,1)

In [ ]:
a = np.random.randn(3,2)
a

In [ ]:
(a*b)+b

In [ ]:
''' Based on Tinrtgu's FTRL code: http://www.kaggle.com/c/avazu-ctr-prediction/forums/t/10927/beat-the-benchmark-with-less-than-1mb-of-memory
'''

from csv import DictReader
from math import exp, copysign, log, sqrt
from datetime import datetime
import random

class FM_FTRL_machine(object):
    
    def __init__(self, fm_dim, fm_initDev, L1, L2, L1_fm, L2_fm, D, alpha, beta, alpha_fm = .1, beta_fm = 1.0, dropoutRate = 1.0):
        ''' initialize the factorization machine.'''
        
        self.alpha = alpha              # learning rate parameter alpha
        self.beta = beta                # learning rate parameter beta
        self.L1 = L1                    # L1 regularizer for first order terms
        self.L2 = L2                    # L2 regularizer for first order terms
        self.alpha_fm = alpha_fm        # learning rate parameter alpha for factorization machine
        self.beta_fm = beta_fm          # learning rate parameter beta for factorization machine
        self.L1_fm = L1_fm              # L1 regularizer for factorization machine weights. Only use L1 after one epoch of training, because small initializations are needed for gradient.
        self.L2_fm = L2_fm              # L2 regularizer for factorization machine weights.
        self.fm_dim = fm_dim            # dimension of factorization.
        self.fm_initDev = fm_initDev    # standard deviation for random intitialization of factorization weights.
        self.dropoutRate = dropoutRate  # dropout rate (which is actually the inclusion rate), i.e. dropoutRate = .8 indicates a probability of .2 of dropping out a feature.
        
        self.D = D
        
        # model
        # n: squared sum of past gradients
        # z: weights
        # w: lazy weights
        
        # let index 0 be bias term to avoid collisions.
        self.n = [0.] * (D + 1) 
        self.z = [0.] * (D + 1)
        self.w = [0.] * (D + 1)
        
        self.n_fm = {}
        self.z_fm = {}
        self.w_fm = {}
    
        
    def init_fm(self, i):
        ''' initialize the factorization weight vector for variable i.
        '''
        if i not in self.n_fm:
            self.n_fm[i] = [0.] * self.fm_dim
            self.w_fm[i] = [0.] * self.fm_dim
            self.z_fm[i] = [0.] * self.fm_dim
            
            for k in range(self.fm_dim): 
                self.z_fm[i][k] = random.gauss(0., self.fm_initDev)
    
    def predict_raw(self, x):
        ''' predict the raw score prior to logit transformation.
        '''
        alpha = self.alpha
        beta = self.beta
        L1 = self.L1
        L2 = self.L2
        alpha_fm = self.alpha_fm
        beta_fm = self.beta_fm
        L1_fm = self.L1_fm
        L2_fm = self.L2_fm
        
        # first order weights model
        n = self.n
        z = self.z
        w = self.w
        
        # FM interaction model
        n_fm = self.n_fm
        z_fm = self.z_fm
        w_fm = self.w_fm
        
        raw_y = 0.
        
        # calculate the bias contribution
        for i in [0]:
            # no regularization for bias
            w[i] = (- z[i]) / ((beta + sqrt(n[i])) / alpha)
            
            raw_y += w[i]
        
        # calculate the first order contribution.
        for i in x:
            sign = -1. if z[i] < 0. else 1. # get sign of z[i]
            
            if sign * z[i] <= L1:
                w[i] = 0.
            else:
                w[i] = (sign * L1 - z[i]) / ((beta + sqrt(n[i])) / alpha + L2)
            
            raw_y += w[i]
        
        len_x = len(x)
        # calculate factorization machine contribution.
        for i in x:
            self.init_fm(i)
            for k in range(self.fm_dim):
                sign = -1. if z_fm[i][k] < 0. else 1.   # get the sign of z_fm[i][k]
                
                if sign * z_fm[i][k] <= L1_fm:
                    w_fm[i][k] = 0.
                else:
                    w_fm[i][k] = (sign * L1_fm - z_fm[i][k]) / ((beta_fm + sqrt(n_fm[i][k])) / alpha_fm + L2_fm)
        
        for i in range(len_x):
            for j in range(i + 1, len_x):
                for k in range(self.fm_dim):
                    raw_y += w_fm[x[i]][k] * w_fm[x[j]][k]
        
        return raw_y
    
    def predict(self, x):
        ''' predict the logit
        '''
        return 1. / (1. + exp(- max(min(self.predict_raw(x), 35.), -35.)))
    
    def dropout(self, x):
        ''' dropout variables in list x
        '''
        for i, var in enumerate(x):
            if random.random() > self.dropoutRate:
                del x[i]
    
    def dropoutThenPredict(self, x):
        ''' first dropout some variables and then predict the logit using the dropped out data.
        '''
        self.dropout(x)
        return self.predict(x)
    
    def predictWithDroppedOutModel(self, x):
        ''' predict using all data, using a model trained with dropout.
        '''
        return 1. / (1. + exp(- max(min(self.predict_raw(x) * self.dropoutRate, 35.), -35.)))
    
    def update(self, x, p, y):
        ''' Update the parameters using FTRL (Follow the Regularized Leader)
        '''
        alpha = self.alpha
        alpha_fm = self.alpha_fm
        
        # model
        n = self.n
        z = self.z
        w = self.w
        
        # FM model
        n_fm = self.n_fm
        z_fm = self.z_fm
        w_fm = self.w_fm
        
        # cost gradient with respect to raw prediction.
        g = p - y
        
        fm_sum = {}      # sums for calculating gradients for FM.
        len_x = len(x)
        
        for i in x + [0]:
            # update the first order weights.
            sigma = (sqrt(n[i] + g * g) - sqrt(n[i])) / alpha
            z[i] += g - sigma * w[i]
            n[i] += g * g
            
            # initialize the sum of the FM interaction weights.
            fm_sum[i] = [0.] * self.fm_dim
        
        # sum the gradients for FM interaction weights.
        for i in range(len_x):
            for j in range(len_x):
                if i != j:
                    for k in range(self.fm_dim):
                        fm_sum[x[i]][k] += w_fm[x[j]][k]
        
        for i in x:
            for k in range(self.fm_dim):
                g_fm = g * fm_sum[i][k]
                sigma = (sqrt(n_fm[i][k] + g_fm * g_fm) - sqrt(n_fm[i][k])) / alpha_fm
                z_fm[i][k] += g_fm - sigma * w_fm[i][k]
                n_fm[i][k] += g_fm * g_fm
    
    def write_w(self, filePath):
        ''' write out the first order weights w to a file.
        '''
        with open(filePath, "w") as f_out:
            for i, w in enumerate(self.w):
                f_out.write("%i,%f\n" % (i, w))
    
    def write_w_fm(self, filePath):
        ''' write out the factorization machine weights to a file.
        '''
        with open(filePath, "w") as f_out:
            for k, w_fm in self.w_fm.iteritems():
                f_out.write("%i,%s\n" % (k, ",".join([str(w) for w in w_fm])))


def logLoss(p, y):
    ''' 
    calculate the log loss cost
    p: prediction [0, 1]
    y: actual value {0, 1}
    '''
    p = max(min(p, 1. - 1e-15), 1e-15)
    return - log(p) if y == 1. else -log(1. - p)

def data(filePath, hashSize, hashSalt):
    ''' generator for data using hash trick
    
    INPUT:
        filePath
        hashSize
        hashSalt: String with which to salt the hash function
    '''
    
    for t, row in enumerate(DictReader(open(filePath))):
        ID = row['id']
        del row['id']
        
        y = 0.
        if 'click' in row:
            if row['click'] == '1':
                y = 1.
            del row['click']
        
        date = int(row['hour'][4:6])
        
        row['hour'] = row['hour'][6:]
        
        x = []
        
        for key in row:
            value = row[key]
            
            index = abs(hash(hashSalt + key + '_' + value)) % hashSize + 1      # 1 is added to hash index because I want 0 to indicate the bias term.
            x.append(index)
        
        yield t, date, ID, x, y