In [1]:
import tensorflow as tf
import numpy as np

In [15]:
x = tf.sparse_placeholder(tf.float32,shape=[None,None])
y = tf.sparse_reduce_sum(x)
z = tf.sparse_to_dense(x.indices,x.dense_shape,x.values)

In [18]:
indices = np.array([[3, 2], [4, 5]], dtype=np.int64)
values = np.array([1.0, 2.0], dtype=np.float32)
shape = np.array([7, 9,], dtype=np.int64)

In [19]:
with tf.Session() as sess:
    print(sess.run(z, feed_dict={
    x: tf.SparseTensorValue(indices, values, shape)}))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]
